FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base
RUN pnpm -v

# 필요한 패키지 설치 (Debian 기반)
RUN apt-get update && apt-get install -y \
    libc6-dev \
    python3 \
    make \
    g++ \
    build-essential \
    libcairo2-dev \
    libpango1.0-dev \
    chromium

RUN pnpm -v

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
ENV NODE_OPTIONS=--max-old-space-size=8192

WORKDIR /usr/src

# 소스 파일 복사
COPY . .

RUN pnpm install
RUN pnpm build

EXPOSE 3000

CMD [ "pnpm", "start" ]
